### ISSUE TITLE
Support for Range/RangeInclusive

### ISSUE THREAD

**Issue by jacogr** [paritytech/scale-info#123]
These are now supported in scale-codec after https://github.com/paritytech/parity-scale-codec/pull/269

It may "just work", but worth a check.

**Comment by dvdplm** [comment]
No, it'll need explicit support I think. I'll see if I can make it happen this week.

**Comment by ascjones** [comment]
Note that this has not made it into a `parity-scale-codec` release yet, but we should be ready for when it does.
