### ISSUE TITLE
Empty tuple is encoded as null in the polkadot SDK

### ISSUE THREAD

**Issue by Diiaablo95** [paritytech/scale-info#134]
After upgrading our parachain to use metadata v14, we now have no way to distinguish whether an element is present or not in a `StorageMap<AccountId32 ()>`, as the `api.query.pallet.storage(key)` returns `null` in both cases. I can see also from polkadotjs apps that the map is a map from `AccountId32` to `Option<Null>`.
So far, the only workaround I found is to fetch ALL the keys via `api.query.pallet.keys` and then filter, but that can get quite expensive if the map has a lot of keys. Is there a more efficient way to check for existence in such a map or, if there is not, would it be possible to fix this issue by encoding empty tuples differently? I am not sure if this issue pertains the SDK side or the chain side.

I also opened an [issue in the @polkadot/api repo](https://github.com/polkadot-js/api/issues/4146).

On the chain side, this is what I get when printing type info for the `()` type:

```rust
Type {
    path: Path {
        segments: [],
    },
    type_params: [],
    type_def: Tuple(
        TypeDefTuple {
            fields: [],
        },
    ),
    docs: [],
}
```

**Comment by ascjones** [comment]
The unit `()` type is indeed described as an empty tuple. That is by design and has to be handled by the client library.

> Is there a more efficient way to check for existence in such a map or

I'm not qualified to provide a good answer here, but perhaps use a `bool` as the value for this, and make it a `Default` storage map so it will return `false` if not present.
