### ISSUE TITLE
Impossible to implement `TypeInfo` for enums with more than 256 variants

### ISSUE THREAD

**Issue by Boiethios** [paritytech/scale-info#136]
The whole ecosystem's derives (`Encode`, `Decode`, `TypeInfo`) don't support big enums well, but in the case of `Encode` and `Decode`, it's not much of an issue because it's easy to implement them by hand, with an index that can exceed an `u8` bound (with an `u16` for example). However, in the case of `TypeInfo`, as far as I understand it, it's impossible to implement the trait for a big enum with the current API since a variant index is typed as an `u8`: https://docs.rs/scale-info/1.0.0/scale_info/build/struct.VariantBuilder.html#method.index.

Is there any reason why it's an `u8`? I guess it could be an `usize` (for example) without breaking any functionality, and it would allow people to include those big enums in the SDK.

What do you think about that?

For reference, this is what we do in our code for now:

```rust
pub enum Ledger {
    // bunch of variants
}

impl TypeInfo for Ledger {
    type Identity = Self;

    fn type_info() -> Type {
        Type::builder()
            .path(Path::new(stringify!(Ledger), module_path!()))
            .composite(Fields::unnamed().field(|f| f.compact::<u16>().type_name("u16")))
    }
}
```

It's inconvenient because we see the enum as a plain `u16`.

**Comment by jsdw** [comment]
partiy-scale-codec encodes enum variants to u8s (see the enum section of https://docs.substrate.io/v3/advanced/scale-codec/).

Since the `TypeInfo` bits relate to the SCALE encoding of types, it inherits the same limitation!

**Comment by ascjones** [comment]
See https://github.com/paritytech/parity-scale-codec/issues/305.

If and when that is implemented we will update `scale-info` accordingly.
