### ISSUE TITLE
The generated `TypeInfo` impl requires T: 'static even when `#[scale_info(skip_type_params(T), bounds())]`

### ISSUE THREAD

**Issue by jsdw** [paritytech/scale-info#138]
If I have a struct like:

```
#[derive(TypeInfo)]
#[scale_info(skip_type_params(T), bounds())]
struct Foo<T> {
   marker: std::marker::PhantomData<T>
}
```

The resulting `TypeInfo` impl still seems to require `T: 'static`, despite it not being used.

**Comment by dvdplm** [comment]
The `'static` bound is added [here](https://github.com/paritytech/scale-info/blob/d13be2a6437493a0ef8ed5a471c16abcc3e424a5/derive/src/trait_bounds.rs#L68-L73) and reflects the requirement of [`std::any::TypId::of`](https://doc.rust-lang.org/stable/std/any/struct.TypeId.html#method.of), which we [use](https://github.com/paritytech/scale-info/blob/d13be2a6437493a0ef8ed5a471c16abcc3e424a5/src/meta_type.rs#L95) to unify different types that are encoded the same via the `Identity` associated type.

Maybe we could be smarter about this though? Can you elaborate on why/where the extra `'static` bound causes a problem?

**Comment by jsdw** [comment]
Thanks! It's not a huge deal, but in `subxt` we have various types that take in a `T: Config` sort of like this:

```
trait Config {
   type Foo;
   type Bar;
}

type MyType<T: Config> {
    marker: std::marker::PhantomData<T>
}
```

The `Config` trait only exists to group together and provide access to some associated types that we might make use of in places (and the thing implementing it will never actually be instantiated).

I decide I want `MyType` to derive `TypeInfo`, so I add that derive like so

```
#[derive(TypeInfo)]
type MyType<T: Config> {
    marker: std::marker::PhantomData<T>
}
```

This fails because `T` doesn't impl `TypeInfo` (and by default all generic params must), so I tell `scale_info` to ignore `T` the best I can:

```
#[derive(TypeInfo)]
#[scale_info(skip_type_params(T), bounds())]
type MyType<T: Config> {
    marker: std::marker::PhantomData<T>
}
```

This still fails because it's still wanting `T: 'static`, which my `Config` trait doesn't guarantee.

The fix is easy: bound `Config` to being `'static`:

```
trait Config: 'static {
   // ...
}
```

But should be unnecessary since I never expect to instantiate `Config` anywhere.

**Comment by dvdplm** [comment]
Digging deeper into this I found [this](https://github.com/paritytech/scale-info/pull/91) to be relevant. I don't think this is possible today, but might be one day ("specialization something something").

**Comment by jsdw** [comment]
Thanks for having a look!

So to summarize, The type that `TypeInfo` is implemented on needs to be `'static` because `TypeId::of::<SomeType>` is used internally and requires `SomeType` to be `'static`. And If you hava a `MyType<T>` somewhere, then `MyType` is only `'static` if `T` is!
