### ISSUE TITLE
Generated metadata includes `struct NonZeroU64(NonZeroU64)`, which is impossible to construct

### ISSUE THREAD

**Issue by isSerge** [paritytech/scale-info#172]
Hi, I hope this is the correct repo to report this. 
Our [node](https://github.com/subspace/subspace) is using `scale-info v2.3.0`. 
It seems SCALE metadata generator creates metadata, which includes `struct NonZeroU64(NonZeroU64)`, which then cannot be constructed:
![image](https://user-images.githubusercontent.com/13568875/206694672-70a67de0-e912-440b-9fea-5c51a267bdf7.png)

**Comment by ascjones** [comment]
Yes, this is fixed in https://github.com/paritytech/scale-info/pull/171, but this looks like it hasn't been released yet. I will do a `2.3.1` release.

**Comment by ascjones** [comment]
https://github.com/paritytech/scale-info/pull/173/
