### ISSUE TITLE
Optionally allow encoding `PhantomData<T>` types

### ISSUE THREAD

**Issue by SkymanOne** [paritytech/scale-info#191]
https://github.com/paritytech/substrate/pull/14750 introduces the persistence of some configured types in the metadata. It uses `PhantomData<T>` to express these types as they don't need to get instantiated.

However, due to #111 these types are not reflected in the metadata.

Is it possible to add an optional flag to persist these fields in the metadata?

**Comment by athei** [comment]
cc @ascjones

**Comment by ascjones** [comment]
I [suggested](https://github.com/paritytech/substrate/pull/14750#pullrequestreview-1578350690) using a wrapper type, let me know if that works

**Comment by athei** [comment]
Thanks. That works.
