### ISSUE TITLE
What are `I256` and `U256` for?

### ISSUE THREAD

**Issue by boundless-forest** [paritytech/scale-info#194]
https://github.com/paritytech/scale-info/blob/master/src/ty/mod.rs#L375-L377

And 

https://github.com/paritytech/scale-info/blob/master/src/ty/mod.rs#L393C49-L395

I noticed that these two types are not impl metadata at all. So what's the point behind this?

```rs
impl_metadata_for_primitives!(
    bool => TypeDefPrimitive::Bool,
    char => TypeDefPrimitive::Char,
    u8 => TypeDefPrimitive::U8,
    u16 => TypeDefPrimitive::U16,
    u32 => TypeDefPrimitive::U32,
    u64 => TypeDefPrimitive::U64,
    u128 => TypeDefPrimitive::U128,
    i8 => TypeDefPrimitive::I8,
    i16 => TypeDefPrimitive::I16,
    i32 => TypeDefPrimitive::I32,
    i64 => TypeDefPrimitive::I64,
    i128 => TypeDefPrimitive::I128,
);
```

**Comment by jsdw** [comment]
I don't think that they are super useful really, and they don't map to Rust primitives unlike the other primitive types.

As such, they will likely be removed eventually; see https://github.com/paritytech/scale-info/pull/181 :)
