### ISSUE TITLE
Not an issue, but can you type info to have reflections in rust ?

### ISSUE THREAD

**Issue by mateuszaaa** [paritytech/scale-info#198]
Essentially if its possible to iterate over fields of struct annotated with TypeInfo and display its names and assigned values? 

https://substrate.stackexchange.com/questions/10529/is-there-any-way-to-extract-method-and-params-of-unchecked-extrinsic-using-s

**Comment by jsdw** [comment]
Types annotated with `#[derive(TypeInfo)]` end up with a `MyType::type_info()` method (see https://docs.rs/scale-info/latest/scale_info/trait.TypeInfo.html). Look through the docs there (specifically at https://docs.rs/scale-info/latest/scale_info/enum.TypeDef.html) and you'll see how to obtain various information about the _type_.

You can't get any information about _values_ though; the macro doesn't know anything about the values of a particular instance. All you get is the _type_ information which is tied to how some instance of that type would be SCALE encoded via `parity-scale-codec`.

If you have some SCALE encoded bytes already, and you have a `scale_info::PortableRegistry` describing the shape of those bytes (this can be constructed from some `TypeInfo`s), then libraries like https://github.com/paritytech/scale-decode can be used to decode those bytes into some type (anything implementing `DecodeAsType` which has a compatible shape), and building on that, https://github.com/paritytech/scale-value offers a `Value` type which is one such target that _any_ SCALE encoded bytes can decode into, and can then be iterated over or whatever to explore the value.

**Comment by mateuszaaa** [comment]
amazing!!! thanks!
