### ISSUE TITLE
Remove PhantomData

### ISSUE THREAD

**Issue by ascjones** [paritytech/scale-info#7]
From @Robbepop comment in https://github.com/type-metadata/type-metadata/pull/42#discussion_r401446838

Probably will need to update derive macro to skip over `PhantomData` fields.

rel #3

**Comment by Robbepop** [comment]
> Probably will need to update derive macro to skip over PhantomData fields.

Note that checks like these should always happen on a type level, never on a syntactical level so this will get a bit more involved in a proc. macro. You might be in need of additional helper traits to help in this process.

**Comment by dvdplm** [comment]
Do I understand this correctly? We want this:

https://github.com/paritytech/scale-info/blob/4188f029052196268b38af62279224ed510125cb/src/tests.rs#L71-L77

…to turn be this:

```rust
	assert_type!(
		i32,
		Type::builder()
			.path(Path::prelude("PhantomData"))
			.type_params(tuple_meta_type!(i32))
			.composite(Fields::unit())
	);
```

(and pass, naturally)?

**Comment by ascjones** [comment]
I believe the idea is that any fields which are `PhantomData` are not even included in a type definition at all (since they have no encoded representation in SCALE). @Robbepop might elaborate more what he means.
