### ISSUE TITLE
Derive does not add bounds for wrapped associated types correctly

### ISSUE THREAD

**Issue by dvdplm** [paritytech/scale-info#73]
The following struct contains an associated type that needs `TypeInfo + 'static` bounds. The derived code does not provide the required bound.

```rust
    trait Colorizer {
        type Property;
    }
    struct Felt {}
    impl Colorizer for Felt {
        type Property = String;
    }
    #[allow(unused)]
    #[derive(TypeInfo)]
    struct Pen<P: Colorizer = Felt> {
        usage: Docs<P>,
        properties: Vec<P::Property>
    }
``` 

`Pen` needs the following bounds:

```
Docs<P>: TypeInfo + 'static,
P: Colorizer + TypeInfo + 'static,
P::Property: TypeInfo + 'static,
```

The derive macro however does not provide the last one, `P::Property: TypeInfo + 'static`.

Macro expansion:

```rust
    const _: () = {
        impl<P: Colorizer> ::scale_info::TypeInfo for Pen<P>
        where
            Docs<P>: ::scale_info::TypeInfo + 'static,
            Vec<P::Property>: ::scale_info::TypeInfo + 'static,
            P: Colorizer + ::scale_info::TypeInfo + 'static,
        {
            type Identity = Self;
            fn type_info() -> ::scale_info::Type {
                ::scale_info::Type::builder()
                    .path(::scale_info::Path::new("Pen", "derive"))
                    .type_params(<[_]>::into_vec(box [::scale_info::meta_type::<P>()]))
                    .composite(
                        ::scale_info::build::Fields::named()
                            .field_of::<Docs<P>>("usage", "Docs<P>")
                            .field_of::<Vec<P::Property>>("properties", "Vec<P::Property>"),
                    )
            }
        };
    };
```

A concrete example of where we need this is https://github.com/paritytech/scale-info/blob/master/src/ty/mod.rs#L65-L81

Notice the odd `Vec<P::Property>: ::scale_info::TypeInfo + 'static,` in the expansion.

**Comment by Robbepop** [comment]
> Notice the odd Vec<P::Property>: ::scale_info::TypeInfo + 'static, in the expansion.

This is to be expected since the macro generates (as all standard proc. macros) trait bounds for all fields and their types.

I think the best we can do is to allow users to customize their trait bounds manually since any hackery to solve this automatically will eventually break other scenarios. The same is done for example in `serde`.

**Comment by dvdplm** [comment]
I was a bit surprised that `Vec<T>: TypeInfo + 'static` is not enough, given that we already have `impl<T> TypeInfo for Vec<T> where T: TypeInfo + 'static,`.

Either way, what do you think about trying a `Visit`-or on the type of each field to recursively collect all the `GenericParam` and add the bounds?

**Comment by Robbepop** [comment]
> Either way, what do you think about trying a Visit-or on the type of each field to recursively collect all the GenericParam and add the bounds?

I am always against doing syntactic analysis in proc. macros since you will always break your neck somewhere and end up with a half-a$$ed solution anyways that will cause confusion to people and make things less transparent. So how about doing what `serde` did and allow users to customize their trait bounds?

**Comment by dvdplm** [comment]
> So how about doing what `serde` did and allow users to customize their trait bounds?

I like this idea, it's pragmatic and solves the problem. It does expose a bigger "API" to users which is always good to avoid. I don't have your deep knowledge/intuition about the possible future pitfalls so if you're convinced parsing the source is eventually going to fail then let's not go there. :)

**Comment by thiolliere** [comment]
This issue is a bit related to https://github.com/paritytech/parity-scale-codec/issues/217

I actually think parity-scale-codec bounds too much generics in some context by visiting every types when it is not needed.
But I never took the time to be sure of this.

> The derive macro however does not provide the last one, `P::Property: TypeInfo + 'static`

I actually don't understand why you want to bound this, is it needed? AFAICT the `Vec<P::Property>: ::scale_info::TypeInfo + 'static` should be enough to ensure that the field properties has type info.

> Either way, what do you think about trying a Visit-or on the type of each field to recursively collect all the GenericParam and add the bounds?

My 2 cents is that this macro should do similar bounding than parity-scale-codec.
And I agree that allowing user to define bounds manually similarly to serde can be useful. Maybe we should do this here and in parity-scale-codec.

**Comment by dvdplm** [comment]
> > The derive macro however does not provide the last one, `P::Property: TypeInfo + 'static`
> 
> I actually don't understand why you want to bound this, is it needed? AFAICT the `Vec<P::Property>: ::scale_info::TypeInfo + 'static` should be enough to ensure that the field properties has type info.

`rustc` seems to think it is needed, but I agree with you that the impl on `Vec<T>` should be enough. Maybe there's something deeper going on here. :/

> And I agree that allowing user to define bounds manually similarly to serde can be useful. Maybe we should do this here and in parity-scale-codec.

We had a call just now about `scale-info` in general and agreed that adding this is useful. I don't think I'll have time to work on it before middle of next week so if you get it done first I'm always happy to steal code! :)

**Comment by thiolliere** [comment]
> rustc seems to think it is needed, but I agree with you that the impl on Vec<T> should be enough. Maybe there's something deeper going on here. :/

I tried to compile:
```rust

trait Colorizer {
	type Property;
}
struct Felt {}
impl Colorizer for Felt {
	type Property = String;
}

#[allow(unused)]
#[derive(scale_info::TypeInfo)]
struct Pen<P: Colorizer = Felt> {
	usage: core::marker::PhantomData<P>,
	properties: Vec<P::Property>
}
```
it fails because:
```
error: defaults for type parameters are only allowed in `struct`, `enum`, `type`, or `trait` definitions.
  --> test_suite/tests/toto.rs:12:12
   |
12 | struct Pen<P: Colorizer = Felt> {
   |            ^
   |
   = note: `#[deny(invalid_type_param_default)]` on by default
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #36887 <https://github.com/rust-lang/rust/issues/36887>

```
Which is due to expanding to:
```
        impl <P: Colorizer = Felt> ::scale_info::TypeInfo for Pen<P> where
```
instead of
```
        impl <P: Colorizer> ::scale_info::TypeInfo for Pen<P> where
```

If I remove `= Felt` in the test, then I have no longer error.

**Comment by dvdplm** [comment]
@thiolliere yeah that's a different bug, #71

**Comment by thiolliere** [comment]
ah ok, in your example when I look at the expanded code I see:
```
impl <T: Form> crate::TypeInfo for Type<T> where
	Path<T>: crate::TypeInfo + 'static,
	TypeDef<T>: crate::TypeInfo + 'static,
	T: Form + crate::TypeInfo + 'static
```
It seems to me it is lacking: `Vec<T::Type>`, but I may be wrong.

Also the issue I linked paritytech/parity-scale-codec#217 is not really related, it is about recursive types.

**Comment by thiolliere** [comment]
I tried locally:
```rust
trait Types {
	type Assoc;
}
#[derive(Encode, Decode)]
struct Assoc<T: Types> {
	a: Vec<T::Assoc>,
}
```
And parity-scale-codec bounds `Vec<T::Assoc>` correctly, because it checks that the first segment is of name `"Assoc"`.

But
```rust
#[derive(Encode, Decode)]
struct Assoc<T: Types> {
	a: Vec<<T>::Assoc>,
}
```
Fails indeed, we need to ensure qself is empty.
