### ISSUE TITLE
Trait bounds: derive as much as is reasonable, `#[scale_info(bounds())]` for the rest

### ISSUE THREAD

**Issue by ascjones** [paritytech/scale-info#78]
In a meeting it was decided that we put forward with `scale-info` in the following way:

- We will go with the "hacks" that have already been implemented for it and for `parity-scale-codec` crates to cover the most common use cases with 80/20 rule.
- For the other 20% of cases that are not covered by the `scale-info` and `parity-scale-codec` derive macros we will provide a feature for users to define custom trait bounds similar to the design `serde` chose. Those custom trait bounds will be replacing the generated ones instead of being additive.
- We might consider in the future to remove the "cruft" of "hacks" for common cases and consider removing them altogether with a major release for both derives.

_Originally posted by @Robbepop in https://github.com/paritytech/scale-info/pull/76#issuecomment-797506544_

**Comment by dvdplm** [comment]
cc @thiolliere

**Comment by ascjones** [comment]
Linking https://github.com/paritytech/parity-scale-codec/pull/263
