### ISSUE TITLE
String Representation

### ISSUE THREAD

**Issue by ascjones** [paritytech/scale-info#9]
- Either we go full way and represent String the same as str or we do the same as I proposed for HashMap where we make it like a tuple struct to be able to drop the vec name for the field.

- Maybe we actually can do better than this? What we actually want is like a type alias, or what do you think? So we could say that a `String` is really just a `str` but still something different.

> A good idea because this way we are not losing information i.e. that the original type was String and not str.

- Yes, but actually I am asking myself if this is useful information with scale-info being a SCALE codec protocol, not a type protocol.

_Originally posted by @Robbepop in https://github.com/type-metadata/type-metadata/pull/42_

**Comment by ascjones** [comment]
In the end we are representing it as `str`, fixed in #3

**Comment by Robbepop** [comment]
I think this is a sane solution since `scale-info` represents SCALE encoding, not type information.
